name: Create MSU Type Bundle

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow
    - name: Build
      id: build
      shell: pwsh
      run: |
        .\CreateBundle.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: msu_types.json
        name: msu_types_${{ steps.build.outputs.tag }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "msu_types.json"
        tag: ${{ steps.build.outputs.tag }}
        omitBody: true
